number_of_hours_worked_per_days = 10
number_of_days_worked_per_week = 5
number_of_weeks_in_THP =11
puts "Travail : #{number_of_hours_worked_per_days*number_of_days_worked_per_week*number_of_weeks_in_THP}"
puts "Et en minutes ça fait : #{number_of_minutes_in_a_days* number_of_hours_worked_per_days*number_of_days_worked_per_week*number_of_weeks_in_THP}"

#"undefined local variable or method", evidement, c'était sur, j'ai pas défini ma variable min_in_a_day...
#j'ai défini 3 var et j'essaye d'en utiliser 4...